# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x07service\x1a\x1bgoogle/protobuf/empty.proto\"@\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\x12\x11\n\tplaylists\x18\x04 \x03(\x05\"3\n\x08Playlist\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05songs\x18\x03 \x03(\x05\"0\n\x04Song\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06\x61rtist\x18\x03 \x01(\t\"\x1d\n\x0bUserRequest\x12\x0e\n\x06userId\x18\x01 \x01(\x05\"%\n\x0fPlaylistRequest\x12\x12\n\nplaylistId\x18\x01 \x01(\x05\"\x1d\n\x0bSongRequest\x12\x0e\n\x06songId\x18\x01 \x01(\x05\"(\n\x08UserList\x12\x1c\n\x05users\x18\x01 \x03(\x0b\x32\r.service.User\"4\n\x0cPlaylistList\x12$\n\tplaylists\x18\x01 \x03(\x0b\x32\x11.service.Playlist\"(\n\x08SongList\x12\x1c\n\x05songs\x18\x01 \x03(\x0b\x32\r.service.Song2\x88\x03\n\x0cMusicService\x12\x35\n\x08GetUsers\x12\x16.google.protobuf.Empty\x1a\x11.service.UserList\x12=\n\x0cGetPlaylists\x12\x16.google.protobuf.Empty\x1a\x15.service.PlaylistList\x12\x35\n\x08GetSongs\x12\x16.google.protobuf.Empty\x1a\x11.service.SongList\x12?\n\x10GetUserPlaylists\x12\x14.service.UserRequest\x1a\x15.service.PlaylistList\x12?\n\x10GetPlaylistSongs\x12\x18.service.PlaylistRequest\x1a\x11.service.SongList\x12I\n\x1aGetPlaylistsContainingSong\x12\x14.service.SongRequest\x1a\x15.service.PlaylistListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=55
  _globals['_USER']._serialized_end=119
  _globals['_PLAYLIST']._serialized_start=121
  _globals['_PLAYLIST']._serialized_end=172
  _globals['_SONG']._serialized_start=174
  _globals['_SONG']._serialized_end=222
  _globals['_USERREQUEST']._serialized_start=224
  _globals['_USERREQUEST']._serialized_end=253
  _globals['_PLAYLISTREQUEST']._serialized_start=255
  _globals['_PLAYLISTREQUEST']._serialized_end=292
  _globals['_SONGREQUEST']._serialized_start=294
  _globals['_SONGREQUEST']._serialized_end=323
  _globals['_USERLIST']._serialized_start=325
  _globals['_USERLIST']._serialized_end=365
  _globals['_PLAYLISTLIST']._serialized_start=367
  _globals['_PLAYLISTLIST']._serialized_end=419
  _globals['_SONGLIST']._serialized_start=421
  _globals['_SONGLIST']._serialized_end=461
  _globals['_MUSICSERVICE']._serialized_start=464
  _globals['_MUSICSERVICE']._serialized_end=856
# @@protoc_insertion_point(module_scope)
