# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x1a\x1bgoogle/protobuf/empty.proto\"-\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\"5\n\x08Playlist\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07songIds\x18\x03 \x03(\x05\"0\n\x04Song\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06\x61rtist\x18\x03 \x01(\t\"\x1d\n\x0bUserRequest\x12\x0e\n\x06userId\x18\x01 \x01(\x05\"%\n\x0fPlaylistRequest\x12\x12\n\nplaylistId\x18\x01 \x01(\x05\"\x1d\n\x0bSongRequest\x12\x0e\n\x06songId\x18\x01 \x01(\x05\" \n\x08UserList\x12\x14\n\x05users\x18\x01 \x03(\x0b\x32\x05.User\",\n\x0cPlaylistList\x12\x1c\n\tplaylists\x18\x01 \x03(\x0b\x32\t.Playlist\" \n\x08SongList\x12\x14\n\x05songs\x18\x01 \x03(\x0b\x32\x05.Song2\xc0\x02\n\x0cMusicService\x12-\n\x08GetUsers\x12\x16.google.protobuf.Empty\x1a\t.UserList\x12\x35\n\x0cGetPlaylists\x12\x16.google.protobuf.Empty\x1a\r.PlaylistList\x12-\n\x08GetSongs\x12\x16.google.protobuf.Empty\x1a\t.SongList\x12/\n\x10GetUserPlaylists\x12\x0c.UserRequest\x1a\r.PlaylistList\x12/\n\x10GetPlaylistSongs\x12\x10.PlaylistRequest\x1a\t.SongList\x12\x39\n\x1aGetPlaylistsContainingSong\x12\x0c.SongRequest\x1a\r.PlaylistListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=46
  _globals['_USER']._serialized_end=91
  _globals['_PLAYLIST']._serialized_start=93
  _globals['_PLAYLIST']._serialized_end=146
  _globals['_SONG']._serialized_start=148
  _globals['_SONG']._serialized_end=196
  _globals['_USERREQUEST']._serialized_start=198
  _globals['_USERREQUEST']._serialized_end=227
  _globals['_PLAYLISTREQUEST']._serialized_start=229
  _globals['_PLAYLISTREQUEST']._serialized_end=266
  _globals['_SONGREQUEST']._serialized_start=268
  _globals['_SONGREQUEST']._serialized_end=297
  _globals['_USERLIST']._serialized_start=299
  _globals['_USERLIST']._serialized_end=331
  _globals['_PLAYLISTLIST']._serialized_start=333
  _globals['_PLAYLISTLIST']._serialized_end=377
  _globals['_SONGLIST']._serialized_start=379
  _globals['_SONGLIST']._serialized_end=411
  _globals['_MUSICSERVICE']._serialized_start=414
  _globals['_MUSICSERVICE']._serialized_end=734
# @@protoc_insertion_point(module_scope)
